"""Provenance Guard — Flask application.

Runs Signal 1 (LLM) + Signal 2 (stylometrics), combines the scores, generates
a transparency label, logs each submission, and supports appeals. See
planning.md.
"""

import json
import os
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from signals.llm_signal import classify_with_llm
from signals.stylo_signal import classify_with_stylometrics

app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    storage_uri="memory://",
)

AUDIT_LOG_PATH = os.path.join(os.path.dirname(__file__), "audit_log.json")


# Transparency label variants (see planning.md, "Transparency Label Variants").
AI_LABEL = (
    "AI-Assisted Content Detected\n"
    "Our analysis found strong indicators that this content was likely "
    "generated or substantially written by an AI tool. Confidence: {pct}%.\n"
    "If you believe this is incorrect, you can submit an appeal below."
)
UNCERTAIN_LABEL = (
    "Attribution Unclear\n"
    "Our analysis found mixed signals for this content. We are not confident "
    "whether this was written by a human or generated by an AI tool. "
    "Confidence: {pct}%.\n"
    "If you are the creator, you can submit an appeal to provide more context."
)
HUMAN_LABEL = (
    "Human-Written Content\n"
    "Our analysis found strong indicators that this content was written by a "
    "human. Confidence: {pct}%. Attribution signals are recorded for platform "
    "transparency."
)


def _attribution_for(score: float) -> str:
    """Map a confidence score to an attribution bucket (see planning.md)."""
    if score >= 0.75:
        return "likely_ai"
    if score <= 0.40:
        return "likely_human"
    return "uncertain"


def get_label(confidence_score: float) -> str:
    """Return the transparency label string for a combined confidence score.

    The percentage shown is directional: for the AI and uncertain labels it is
    the AI-likeness score; for the human label it is confidence the text is
    human (1 - score).
    """
    if confidence_score >= 0.75:
        return AI_LABEL.format(pct=round(confidence_score * 100))
    if confidence_score <= 0.40:
        return HUMAN_LABEL.format(pct=round((1 - confidence_score) * 100))
    return UNCERTAIN_LABEL.format(pct=round(confidence_score * 100))


def _read_audit_log() -> list:
    """Return all audit log entries, or an empty list if none exist yet."""
    try:
        with open(AUDIT_LOG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def write_audit_entry(entry: dict) -> None:
    """Append a structured entry to audit_log.json."""
    entries = _read_audit_log()
    entries.append(entry)
    with open(AUDIT_LOG_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2)


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute; 100 per day")
def submit():
    """Accept content, run both signals, log the result, and return a verdict.

    Expects JSON (or form) with `text` and `creator_id`.
    """
    data = request.get_json(silent=True) or request.form

    text = (data.get("text") or "").strip()
    creator_id = (data.get("creator_id") or "").strip()

    if not text:
        return jsonify({"error": "field 'text' is required and must not be empty"}), 400
    if not creator_id:
        return jsonify({"error": "field 'creator_id' is required"}), 400

    llm_score = classify_with_llm(text)
    stylo_score = classify_with_stylometrics(text)
    combined_score = (llm_score * 0.7) + (stylo_score * 0.3)
    attribution = _attribution_for(combined_score)

    content_id = str(uuid.uuid4())
    label = get_label(combined_score)

    entry = {
        "content_id": content_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "creator_id": creator_id,
        "text": text,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "combined_score": combined_score,
        "confidence": combined_score,
        "attribution": attribution,
        "label": label,
        "status": "classified",
    }
    write_audit_entry(entry)

    return jsonify(
        {
            "content_id": content_id,
            "attribution": attribution,
            "confidence": combined_score,
            "label": label,
        }
    )


@app.route("/appeal", methods=["POST"])
def appeal():
    """Accept an appeal for a prior classification.

    Expects JSON (or form) with `content_id` and `creator_reasoning`. Finds the
    matching classification entry, flips its status to "under_review", appends
    an appeal record, and returns a confirmation. No re-classification is done.
    """
    data = request.get_json(silent=True) or request.form

    content_id = (data.get("content_id") or "").strip()
    creator_reasoning = (data.get("creator_reasoning") or "").strip()

    if not content_id:
        return jsonify({"error": "field 'content_id' is required"}), 400
    if not creator_reasoning:
        return jsonify({"error": "field 'creator_reasoning' is required"}), 400

    entries = _read_audit_log()
    original = next(
        (
            e
            for e in entries
            if e.get("content_id") == content_id and e.get("type") != "appeal"
        ),
        None,
    )
    if original is None:
        return jsonify({"error": f"no entry found for content_id '{content_id}'"}), 404

    original["status"] = "under_review"

    appeal_record = {
        "type": "appeal",
        "content_id": content_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "creator_reasoning": creator_reasoning,
        "original_attribution": original.get("attribution"),
        "original_confidence": original.get("confidence"),
    }
    entries.append(appeal_record)

    with open(AUDIT_LOG_PATH, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2)

    return jsonify(
        {
            "status": "under_review",
            "message": (
                f"Appeal received for content {content_id}. "
                "Its status is now under_review."
            ),
        }
    )


@app.route("/log", methods=["GET"])
def log():
    """Return all audit log entries."""
    return jsonify({"entries": _read_audit_log()})


if __name__ == "__main__":
    app.run(debug=True)
